apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  cloudwatch.yaml: |
    apiVersion: 1
    datasources:
      - name: CloudWatch
        uid: cloudwatch
        type: cloudwatch
        access: proxy
        jsonData:
          authType: default
          defaultRegion: us-east-1