apiVersion: v1
kind: Service
metadata:
  name: trade-ingestion-service
  labels:
    app: trade-ingestion-service
spec:
  type: LoadBalancer
  selector:
    app: trade-ingestion-service
  ports:
    - name: http
      port: 80
      targetPort: 8081