apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: case-management-service
  template:
    metadata:
      labels:
        app: case-management-service
    spec:
      containers:
        - name: case-management-service
          image: 674326380423.dkr.ecr.us-east-1.amazonaws.com/surveillance-prod/case-management-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://surveillance-prod-db.ccfkou6gmo5z.us-east-1.rds.amazonaws.com:5432/surveillance?currentSchema=case_management"
            - name: SPRING_DATASOURCE_USERNAME
              value: "surveillance"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "b-2.surveillanceprod.5m8kk8.c11.kafka.us-east-1.amazonaws.com:9094,b-1.surveillanceprod.5m8kk8.c11.kafka.us-east-1.amazonaws.com:9094"
            - name: SPRING_KAFKA_SECURITY_PROTOCOL
              value: "SSL"
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              value: "SSL"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"