apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-monitor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-monitor-service
  template:
    metadata:
      labels:
        app: activity-monitor-service
    spec:
      containers:
        - name: activity-monitor-service
          image: 674326380423.dkr.ecr.us-east-1.amazonaws.com/surveillance-prod/activity-monitor-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://surveillance-prod-db.ccfkou6gmo5z.us-east-1.rds.amazonaws.com:5432/surveillance?currentSchema=activity_monitor"
            - name: SPRING_DATASOURCE_USERNAME
              value: "surveillance"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: msk-secret
                  key: brokers
            - name: SPRING_KAFKA_SECURITY_PROTOCOL
              value: "SSL"
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              value: "SSL"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: ""
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SSL_TRUSTSTORE_TYPE
              value: "PKCS12"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SSL_ENABLED_PROTOCOLS
              value: "TLSv1.2"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SSL_PROTOCOL
              value: "TLSv1.2"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SECURITY_PROTOCOL
              value: "SSL"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"